image: openjdk:11

before_script:
  - chmod +x run.sh
  - java --version # print java version for debugging

stages:
  - build
  - test

build:
  stage: build
  script:
    - ./run.sh compile
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push

test:
  stage: test
  script:
    - ./run.sh test
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
